/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c Transaction -p com.deepin.daemon.authority.Transaction transaction.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef COM_DEEPIN_DAEMON_AUTHORITY_TRANSACTION_H
#define COM_DEEPIN_DAEMON_AUTHORITY_TRANSACTION_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.daemon.Authority.Transaction
 */
class Transaction: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.daemon.Authority.Transaction"; }

public:
    Transaction(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~Transaction();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Authenticate()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Authenticate"), argumentList);
    }

    inline QDBusPendingReply<> End()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("End"), argumentList);
    }

    inline QDBusPendingReply<> SetUser(const QString &user)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user);
        return asyncCallWithArgumentList(QStringLiteral("SetUser"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace deepin {
    namespace daemon {
      namespace authority {
        typedef ::Transaction Transaction;
      }
    }
  }
}
#endif
